/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as MissionControlRouteImport } from './routes/mission-control'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as SystemHealthRouteImport } from './routes/system-health'
import { Route as PatientsIdRouteImport } from './routes/patients.$id'
import { Route as WardIdAnalyticsRouteImport } from './routes/ward.$id.analytics'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionControlRoute = MissionControlRouteImport.update({
  id: '/mission-control',
  path: '/mission-control',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemHealthRoute = SystemHealthRouteImport.update({
  id: '/system-health',
  path: '/system-health',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIdRoute = PatientsIdRouteImport.update({
  id: '/patients/$id',
  path: '/patients/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WardIdAnalyticsRoute = WardIdAnalyticsRouteImport.update({
  id: '/ward/$id/analytics',
  path: '/ward/$id/analytics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/compare': typeof CompareRoute
  '/mission-control': typeof MissionControlRoute
  '/notifications': typeof NotificationsRoute
  '/simulator': typeof SimulatorRoute
  '/system-health': typeof SystemHealthRoute
  '/patients/$id': typeof PatientsIdRoute
  '/ward/$id/analytics': typeof WardIdAnalyticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/compare': typeof CompareRoute
  '/mission-control': typeof MissionControlRoute
  '/notifications': typeof NotificationsRoute
  '/simulator': typeof SimulatorRoute
  '/system-health': typeof SystemHealthRoute
  '/patients/$id': typeof PatientsIdRoute
  '/ward/$id/analytics': typeof WardIdAnalyticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/compare': typeof CompareRoute
  '/mission-control': typeof MissionControlRoute
  '/notifications': typeof NotificationsRoute
  '/simulator': typeof SimulatorRoute
  '/system-health': typeof SystemHealthRoute
  '/patients/$id': typeof PatientsIdRoute
  '/ward/$id/analytics': typeof WardIdAnalyticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/compare'
    | '/mission-control'
    | '/notifications'
    | '/simulator'
    | '/system-health'
    | '/patients/$id'
    | '/ward/$id/analytics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/compare'
    | '/mission-control'
    | '/notifications'
    | '/simulator'
    | '/system-health'
    | '/patients/$id'
    | '/ward/$id/analytics'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/analytics'
    | '/compare'
    | '/mission-control'
    | '/notifications'
    | '/simulator'
    | '/system-health'
    | '/patients/$id'
    | '/ward/$id/analytics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CompareRoute: typeof CompareRoute
  MissionControlRoute: typeof MissionControlRoute
  NotificationsRoute: typeof NotificationsRoute
  SimulatorRoute: typeof SimulatorRoute
  SystemHealthRoute: typeof SystemHealthRoute
  PatientsIdRoute: typeof PatientsIdRoute
  WardIdAnalyticsRoute: typeof WardIdAnalyticsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission-control': {
      id: '/mission-control'
      path: '/mission-control'
      fullPath: '/mission-control'
      preLoaderRoute: typeof MissionControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-health': {
      id: '/system-health'
      path: '/system-health'
      fullPath: '/system-health'
      preLoaderRoute: typeof SystemHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$id': {
      id: '/patients/$id'
      path: '/patients/$id'
      fullPath: '/patients/$id'
      preLoaderRoute: typeof PatientsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ward/$id/analytics': {
      id: '/ward/$id/analytics'
      path: '/ward/$id/analytics'
      fullPath: '/ward/$id/analytics'
      preLoaderRoute: typeof WardIdAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AnalyticsRoute: AnalyticsRoute,
  CompareRoute: CompareRoute,
  MissionControlRoute: MissionControlRoute,
  NotificationsRoute: NotificationsRoute,
  SimulatorRoute: SimulatorRoute,
  SystemHealthRoute: SystemHealthRoute,
  PatientsIdRoute: PatientsIdRoute,
  WardIdAnalyticsRoute: WardIdAnalyticsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
